config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  mount Sidekiq::Web, at: "/sidekiq"

  devise_for :admins, controllers:  {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: "dashboard#index"
    resources :bicycle_parkings
  end
  root "map#index"
  resources :search, only: :index
  resources :about, only: :index

  get "*not_found" => "application#routing_error"
end

app/views/layouts/admin/_navbar.html.erb
<nav class="sticky top-0 z-20 w-full bg-white shadow mb-4">
  <div class="flex items-center justify-between md:justify-end mx-auto p-4">
    <% if admin_signed_in? %>
      <button class="md:hidden" data-controller="sidebar" data-action="sidebar#open">
        <div class="hover:cursor-pointer text-gray-500 hover:text-gray-800">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
        </div>
      </button>
      <div class="w-auto" id="navbar-default">
        <ul class="font-medium flex flex-col">
          <li>
            <div data-controller="dropdown" class="relative">
              <button type="button" data-action="dropdown#toggle click@window->dropdown#hide" class="flex items-center toggle-user-icon">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M17.982 18.725A7.488 7.488 0 0 0 12 15.75a7.488 7.488 0 0 0-5.982 2.975m11.963 0a9 9 0 1 0-11.963 0m11.963 0A8.966 8.966 0 0 1 12 21a8.966 8.966 0 0 1-5.982-2.275M15 9.75a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
                </svg>
              </button>
              <div
                data-dropdown-target="menu"
                class="hidden transition transform origin-top-right absolute right-0 py-2 min-w-44 bg-white rounded shadow text-gray-500 text-sm"
                data-transition-enter-from="opacity-0 scale-95"
                data-transition-enter-to="opacity-100 scale-100"
                data-transition-leave-from="opacity-100 scale-100"
                data-transition-leave-to="opacity-0 scale-95">
                <div class="py-1 px-2">
                  <%= link_to "プロフィール", "#" %>
                </div>
                <div class="py-1 px-2">
                  <%= link_to "設定", "#" %>
                </div>
                <hr class="my-2 h-px border-0 bg-gray-300">
                <div class="py-1 px-2">
                  <%= button_to "ログアウト", destroy_admin_session_path, method: :delete %>
                </div>
              </div>
            </div>
          </li>
        </ul>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/admin/_sidebar.html.erb
<div>
  <div
    id="sidebar-background"
    class="fixed inset-0 bg-slate-900 bg-opacity-30 z-40 md:hidden bg-opacity-30 opacity-0 pointer-events-none"
    data-controller="sidebar"
    data-action="click->sidebar#close">
  </div>
  <div id="sidebar" class="absolute left-0 top-0 z-50 md:w-[200px] overflow-y-hidden h-screen p-4 bg-sidebar text-white md:block md:static transition-all duration-500 ease-in-out md:translate-x-0 -translate-x-64">
    <div class="flex items-center justify-between px-2">
      <%= image_tag "bicycle.png", class: "w-7 h-7" %>
      <button
        class="text-slate-500 hover:text-slate-200 md:hidden"
        data-controller="sidebar"
        data-action="sidebar#close">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M10.5 19.5 3 12m0 0 7.5-7.5M3 12h18" />
        </svg>
      </button>
    </div>
    <div class="text-slate-500 text-sm px-2 mt-8">
      MENU
    </div>

    <ul>
      <li class="mt-4">
        <%= link_to admin_root_path do %>
          <div class="p-2 flex items-center gap-2 rounded text-sm font-bold hover:bg-sidebar-hover">
            <div>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M7.5 14.25v2.25m3-4.5v4.5m3-6.75v6.75m3-9v9M6 20.25h12A2.25 2.25 0 0 0 20.25 18V6A2.25 2.25 0 0 0 18 3.75H6A2.25 2.25 0 0 0 3.75 6v12A2.25 2.25 0 0 0 6 20.25Z" />
              </svg>
            </div>
            <div class="">
              ダッシュボード
            </div>
          </div>
        <% end %>
      </li>
      <li class="mt-4">
        <%= link_to admin_bicycle_parkings_path do %>
          <div class="p-2 flex items-center gap-2 rounded text-sm font-bold hover:bg-sidebar-hover">
            <div class="w-6 h-6 p-[1px]">
              <%= image_tag "bicycle.svg", class: "text-white" %>
            </div>
            <div class="">
              駐輪場一覧
            </div>
          </div>
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BicycleParking</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="bg-blue-50">
    <div class="flex h-screen overflow-hidden">
      <!-- ==== Sidebar Start ==== -->
      <% if admin_signed_in? %>
        <%= render "layouts/admin/sidebar" %>
      <% end %>
      <!-- ==== Sidebar End ==== -->
      <div class="relative flex flex-col flex-1 overflow-y-auto overflow-x-hidden mb-4">
        <%= render "layouts/admin/navbar" %>
        <%= render "shared/flash" %>
        <main class="container mx-auto px-2">
          <%= yield %>
        </main>
      </div>
    </div>
  </body>
</html>