config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  mount Sidekiq::Web, at: "/sidekiq"

  devise_for :admins, controllers:  {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: "dashboard#index"
    resources :bicycle_parkings
  end
  root "map#index"
  resources :search, only: :index
  resources :about, only: :index

  get "*not_found" => "application#routing_error"
end

app/models/bicycle_parking.rb
class BicycleParking < ApplicationRecord
  has_one_attached :image

  with_options presence: true do
    validates :name, uniqueness: true
    validates :location
    validates :opening_hours
    validates :motorcycle_price, if: :motorcycle_parkable?
    validates :latitude
    validates :longitude
    with_options numericality: {only_integer: true, greater_than_or_equal_to: 0} do
      validates :bicycle_capacity
      validates :motorized_bicycle_under_50cc_capacity
      validates :motorized_bicycle_under_125cc_capacity
      validates :bicycle_and_motorized_bicycle_under_50cc_capacity
      validates :motorcycle_capacity
    end
  end

  scope :motorcycle_parkable, -> { where("motorcycle_capacity > 0") }
  scope :motorized_bicycle_under_50cc_parkable, -> { where("motorized_bicycle_under_50cc_capacity > 0 or bicycle_and_motorized_bicycle_under_50cc_capacity > 0") }
  scope :motorized_bicycle_under_125cc_parkable, -> { where("motorized_bicycle_under_125cc_capacity > 0") }
  scope :available_all_day, -> { where(opening_hours: "終日") }
  scope :default_order, -> { order(created_at: :desc) }

  def motorized_bicycle_under_50cc_parkable?
    motorized_bicycle_under_50cc_capacity > 0 ||
      bicycle_and_motorized_bicycle_under_50cc_capacity > 0
  end

  def motorized_bicycle_under_125cc_parkable?
    motorized_bicycle_under_125cc_capacity > 0
  end

  def motorcycle_parkable?
    motorcycle_capacity > 0
  end
end

app/controllers/admin/bicycle_parkings_controller.rb
class Admin::BicycleParkingsController < Admin::ApplicationController
  before_action :set_bicycle_parking, only: %i[show edit update destroy]
  before_action :set_access_token, only: :show
  before_action :set_japan_style_url, only: :show

  def index
    @bicycle_parkings = BicycleParking.default_order
  end

  def show
    @bicycle_parking_information = [{latitude: @bicycle_parking.latitude, longitude: @bicycle_parking.longitude, discription: render_to_string(partial: "map/discription", locals: {parking: @bicycle_parking})}]
  end

  def new
    @bicycle_parking = BicycleParking.new
  end

  def edit
  end

  def create
    @bicycle_parking = BicycleParking.new(bicycle_parking_params)
    @bicycle_parking.image.attach(params[:bicycle_parking][:image])
    if @bicycle_parking.save
      redirect_to admin_bicycle_parkings_path, notice: "作成しました"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @bicycle_parking.update(bicycle_parking_params)
      redirect_to admin_bicycle_parkings_path, notice: "更新しました"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @bicycle_parking.destroy!
    redirect_to admin_bicycle_parkings_path, notice: "削除しました"
  end

  private

  def set_bicycle_parking
    @bicycle_parking = BicycleParking.find(params[:id])
  end

  def set_japan_style_url
    @mapbox_japan_style = ENV["MAPBOX_JAPAN_STYLE"]
  end

  def set_access_token
    @mapbox_access_token = ENV["MAPBOX_ACCESS_TOKEN"]
  end

  def bicycle_parking_params
    params.require(:bicycle_parking).permit(
      :name,
      :location,
      :opening_hours,
      :bicycle_capacity,
      :motorized_bicycle_under_50cc_capacity,
      :motorized_bicycle_under_125cc_capacity,
      :bicycle_and_motorized_bicycle_under_50cc_capacity,
      :motorcycle_capacity,
      :motorcycle_price,
      :latitude,
      :longitude,
      :published,
      :image
    )
  end
end

app/helpers/bicycle_parkings_helper.rb
module BicycleParkingsHelper
  def capacity_text(parking)
    if parking.bicycle_and_motorized_bicycle_under_50cc_capacity > 0
      "自転車・原付(50cc以下)合わせて#{parking.bicycle_and_motorized_bicycle_under_50cc_capacity}台"
    else
      capacity_text = "自転車#{parking.bicycle_capacity}台"
      capacity_text << "、原付(50cc以下)#{parking.motorized_bicycle_under_50cc_capacity}台" if parking.motorized_bicycle_under_50cc_capacity > 0
      capacity_text << "、原付(125cc以下)#{parking.motorized_bicycle_under_125cc_capacity}台" if parking.motorized_bicycle_under_125cc_capacity > 0
      capacity_text << "、自動二輪車#{parking.motorcycle_capacity}台" if parking.motorcycle_capacity > 0
      capacity_text
    end
  end

  def status_text(parking)
    parking.published ? "公開中" : "非公開"
  end

  def status_style(parking)
    parking.published ?
      "bg-blue-100 text-blue-800 px-2.5 py-0.5 rounded"
      :
      "bg-red-100 text-red-800 px-2.5 py-0.5 rounded"
  end
end

app/views/admin/bicycle_parkings/_bicycle_parking.html.erb
<tr class="border-b border-neutral-200">
  <td class="px-4 py-1"><%= bicycle_parking.name %></td>
  <td class="px-4 py-1"><%= bicycle_parking.location %></td>
  <td class="px-4 py-1"><%= bicycle_parking.opening_hours %></td>
  <td class="px-4 py-1"><span class="<%= status_style(bicycle_parking) %>"><%= status_text(bicycle_parking) %></span></td>
  <td class="px-4 py-1">
    <div class="flex gap-2">
      <div data-controller="popover">
        <%= link_to admin_bicycle_parking_path(bicycle_parking), data: { action: "mouseenter->popover#show mouseleave->popover#hide" }, class: "text-blue-500 hover:text-blue-700 relative" do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M2.036 12.322a1.012 1.012 0 0 1 0-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178Z" />
            <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
          </svg>
          <template data-popover-target="content">
            <div data-popover-target="card">
              <p class="absolute top-[-22px] left-[-6px] bg-white rounded text-xs w-[40px] py-1 text-center shadow">詳細</p>
            </div>
          </template>
        <% end %>
      </div>
      <div data-controller="popover">
        <%= link_to edit_admin_bicycle_parking_path(bicycle_parking), data: { action: "mouseenter->popover#show mouseleave->popover#hide" }, class: "text-red-500 hover:text-red-700 relative" do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0 1 15.75 21H5.25A2.25 2.25 0 0 1 3 18.75V8.25A2.25 2.25 0 0 1 5.25 6H10" />
          </svg>
          <template data-popover-target="content">
            <div data-popover-target="card">
              <p class="absolute top-[-22px] left-[-6px] bg-white rounded text-xs w-[40px] py-1 text-center shadow">編集</p>
            </div>
          </template>
        <% end %>
      </div>
    </div>
  </td>
</tr>

app/views/admin/bicycle_parkings/_form.html.erb
<div class="bg-white rounded py-4">
  <%= form_with(model: [:admin, bicycle_parking], html: { class: "mx-auto w-2/3" }, data: { controller: "bicycle-parkings", action: "input->bicycle-parkings#validSubmit" }) do |f| %>
    <%= render "shared/error_messages", resource: bicycle_parking %>
    <%#= 名称 %>
    <div class="mb-4">
      <%= f.label :name, id: "name", class: "text-gray-700 text-sm font-bold" %><span class="text-red-500 ml-1">*</span>
      <%= f.text_field :name, class: "shadow border rounded outline-none w-full py-2 px-3 text-gray-700", placeholder: "大分駅南口駐輪場", data: { bicycle_parkings_target: "name", action: "input->bicycle-parkings#nameValidation" } %>
      <p data-bicycle-parkings-target="error_name" class="text-xs"></p>
    </div>

    <%#= 所在地 %>
    <div class="mb-4">
      <%= f.label :location, id: "location", class: "text-gray-700 text-sm font-bold" %><span class="text-red-500 ml-1">*</span>
      <%= f.text_field :location, class: "shadow border rounded outline-none w-full py-2 px-3 text-gray-700", placeholder: "大分市金池南1丁目107番", data: { bicycle_parkings_target: "location", action: "input->bicycle-parkings#locationValidation" } %>
      <p data-bicycle-parkings-target="error_location" class="text-xs"></p>
    </div>

    <%#= 開場時間 %>
    <div class="mb-4">
      <%= f.label :opening_hours, id: "opening_hours", class: "text-gray-700 text-sm font-bold" %><span class="text-red-500 ml-1">*</span>
      <%= f.text_field :opening_hours, class: "shadow border rounded outline-none w-full py-2 px-3 text-gray-700", placeholder: "終日", data: { bicycle_parkings_target: "opening_hours", action: "input->bicycle-parkings#openingHoursValidation" } %>
      <p data-bicycle-parkings-target="error_opening_hours" class="text-xs"></p>
    </div>

    <%#= 自転車収容台数 %>
    <div class="mb-4">
      <%= f.label :bicycle_capacity, id: "bicycle_capacity", class: "text-gray-700 text-sm font-bold" %><span class="text-red-500 ml-1">*</span>
      <%= f.number_field :bicycle_capacity, class: "shadow border rounded outline-none w-full py-2 px-3 text-gray-700", data: { bicycle_parkings_target: "bicycle_capacity", action: "input->bicycle-parkings#bicycleCapacityValidation" } %>
      <p data-bicycle-parkings-target="error_bicycle_capacity" class="text-xs"></p>
    </div>

    <%#= 50cc以下の原動機付自転車収容台数 %>
    <div class="mb-4">
      <%= f.label :motorized_bicycle_under_50cc_capacity, id: "motorized_bicycle_under_50cc_capacity", class: "text-gray-700 text-sm font-bold" %><span class="text-red-500 ml-1">*</span>
      <%= f.number_field :motorized_bicycle_under_50cc_capacity, class: "shadow border rounded outline-none w-full py-2 px-3 text-gray-700", data: { bicycle_parkings_target: "motorized_bicycle_under_50cc_capacity", action: "input->bicycle-parkings#motorizedBicycleUnder50ccCapacityValidation" } %>
      <p data-bicycle-parkings-target="error_motorized_bicycle_under_50cc_capacity" class="text-xs"></p>
    </div>

    <%#= 125cc以下の原動機付自転車収容台数 %>
    <div class="mb-4">
      <%= f.label :motorized_bicycle_under_125cc_capacity, id: "motorized_bicycle_under_125cc_capacity", class: "text-gray-700 text-sm font-bold" %><span class="text-red-500 ml-1">*</span>
      <%= f.number_field :motorized_bicycle_under_125cc_capacity, class: "shadow border rounded outline-none w-full py-2 px-3 text-gray-700", data: { bicycle_parkings_target: "motorized_bicycle_under_125cc_capacity", action: "input->bicycle-parkings#motorizedBicycleUnder125ccCapacityValidation" } %>
      <p data-bicycle-parkings-target="error_motorized_bicycle_under_125cc_capacity" class="text-xs"></p>
    </div>

    <%#= 自転車・50cc以下の原動機付自転車収容台数 %>
    <div class="mb-4">
      <%= f.label :bicycle_and_motorized_bicycle_under_50cc_capacity, id: "bicycle_and_motorized_bicycle_under_50cc_capacity", class: "text-gray-700 text-sm font-bold" %><span class="text-red-500 ml-1">*</span>
      <%= f.number_field :bicycle_and_motorized_bicycle_under_50cc_capacity, class: "shadow border rounded outline-none w-full py-2 px-3 text-gray-700", data: { bicycle_parkings_target: "bicycle_and_motorized_bicycle_under_50cc_capacity", action: "input->bicycle-parkings#bicycleAndMotorizedBicycleUnder50ccCapacityValidation" } %>
      <p data-bicycle-parkings-target="error_bicycle_and_motorized_bicycle_under_50cc_capacity" class="text-xs"></p>
    </div>

    <%#= 自動二輪車収容台数 %>
    <div class="mb-4">
      <%= f.label :motorcycle_capacity, id: "motorcycle_capacity", class: "text-gray-700 text-sm font-bold" %><span class="text-red-500 ml-1">*</span>
      <%= f.number_field :motorcycle_capacity, class: "shadow border rounded outline-none w-full py-2 px-3 text-gray-700", data: { bicycle_parkings_target: "motorcycle_capacity", action: "input->bicycle-parkings#motorcycleCapacityValidation" } %>
      <p data-bicycle-parkings-target="error_motorcycle_capacity" class="text-xs"></p>
    </div>

    <%#= 自動二輪車料金 %>
    <div class="mb-4">
      <%= f.label :motorcycle_price, class: "text-gray-700 text-sm font-bold" %>
      <%= f.text_field :motorcycle_price, class: "shadow border rounded outline-none w-full py-2 px-3 text-gray-700" %>
    </div>

    <%#= 緯度 %>
    <div class="mb-4">
      <%= f.label :latitude, id: "latitude", class: "text-gray-700 text-sm font-bold" %><span class="text-red-500 ml-1">*</span>
      <%= f.text_field :latitude, class: "shadow border rounded outline-none w-full py-2 px-3 text-gray-700", data: { bicycle_parkings_target: "latitude", action: "input->bicycle-parkings#latitudeValidation" } %>
      <p data-bicycle-parkings-target="error_latitude" class="text-xs"></p>
    </div>

    <%#= 経度 %>
    <div class="mb-4">
      <%= f.label :longitude, id: "longitude", class: "text-gray-700 text-sm font-bold" %><span class="text-red-500 ml-1">*</span>
      <%= f.text_field :longitude, class: "shadow border rounded outline-none w-full py-2 px-3 text-gray-700", data: { bicycle_parkings_target: "longitude", action: "input->bicycle-parkings#longitudeValidation" } %>
      <p data-bicycle-parkings-target="error_longitude" class="text-xs"></p>
    </div>

    <%#= 画像 %>
    <div class="mb-4">
      <%= f.label :image, class: "text-gray-700 text-sm font-bold" %>
      <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png", class: "block w-full text-sm border cursor-pointer file:cursor-pointer rounded-md file:mr-4 file:rounded-l-md file:border-0 bg-gray-50 file:bg-gray-800 file:py-2.5 file:px-4 file:text-sm file:font-semibold file:text-white hover:file:bg-primary-700 focus:outline-none disabled:pointer-events-none disabled:opacity-60" %>
    </div>

    <%#= 公開ステータス %>
    <div class="mb-4 flex items-center gap-2">
      <%= f.label :published, "公開する", class: "text-gray-700 text-sm font-bold" %>
      <%= f.check_box :published, class: "h-5 w-5 rounded outline-none border-gray-300 shadow-sm" %>
    </div>

    <%= f.submit yield(:button_text), class: "#{yield(:button_color)} text-white text-sm font-bold py-2 px-4 rounded", disabled: true, data: { bicycle_parkings_target: "submit" } %>
  <% end %>
</div>

app/views/admin/bicycle_parkings/edit.html.erb
<% provide(:button_text, "編集") %>
<% provide(:button_color, "bg-blue-500 hover:bg-blue-700") %>

<div class="flex flex-col gap-3 md:flex-row md:justify-between mb-4">
  <div class="text-xm font-bold">
    駐輪場編集
  </div>
  <div class="flex items-center gap-2 text-xs">
    <%= link_to "ダッシュボード /", admin_root_path, class: "text-gray-500" %>
    <%= link_to "駐輪場一覧 /", admin_bicycle_parkings_path, class: "text-gray-500" %>
    <div class="text-blue-500">
      駐輪場編集
    </div>
    </div>
  </div>
  <%= render "form", bicycle_parking: @bicycle_parking %>
</div>

app/views/admin/bicycle_parkings/index.html.erb
<div class="flex flex-col gap-3 md:flex-row md:justify-between mb-4">
  <div class="flex items-center gap-2">
    <div class="text-xm font-bold">
      駐輪場一覧
    </div>
    <div data-controller="popover">
      <%= link_to new_admin_bicycle_parking_path, data: { action: "mouseenter->popover#show mouseleave->popover#hide" }, class: "text-blue-500 hover:text-blue-700 relative" do %>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
          <path fill-rule="evenodd" d="M12 2.25c-5.385 0-9.75 4.365-9.75 9.75s4.365 9.75 9.75 9.75 9.75-4.365 9.75-9.75S17.385 2.25 12 2.25ZM12.75 9a.75.75 0 0 0-1.5 0v2.25H9a.75.75 0 0 0 0 1.5h2.25V15a.75.75 0 0 0 1.5 0v-2.25H15a.75.75 0 0 0 0-1.5h-2.25V9Z" clip-rule="evenodd" />
        </svg>
        <template data-popover-target="content">
            <div data-popover-target="card">
              <p class="absolute top-[-24px] left-[-18px] bg-white rounded text-xs w-[60px] py-1 text-center shadow">新規作成</p>
            </div>
          </template>
      <% end %>
    </div>
  </div>
  <div class="flex items-center gap-2 text-xs">
    <%= link_to "ダッシュボード /", admin_root_path, class: "text-gray-500" %>
    <div class="text-blue-500">
      駐輪場一覧
    </div>
  </div>
</div>
<div class="max-w-full overflow-x-auto">
  <table class="w-full table-auto text-left text-xs bg-white">
    <thead class="border-b-2 border-neutral-200">
      <tr>
        <th class="min-w-[150px] px-4 py-2">名称</th>
        <th class="min-w-[240px] px-4 py-2">所在地</th>
        <th class="min-w-[150px] px-4 py-2">開場時間</th>
        <th class="min-w-[95px] px-4 py-2">ステータス</th>
        <th class="min-w-[50px] px-4 py-2"></th>
      </tr>
    </thead>
    <tbody>
      <%= render @bicycle_parkings %>
    </tbody>
  </table>
</div>

app/views/admin/bicycle_parkings/new.html.erb
<% provide(:button_text, '作成') %>
<% provide(:button_color, "bg-gray-400") %>

<div class="flex flex-col gap-3 md:flex-row md:justify-between mb-4">
  <div class="text-xm font-bold">
    駐輪場作成
  </div>
  <div class="flex items-center gap-2 text-xs">
    <%= link_to "ダッシュボード /", admin_root_path, class: "text-gray-500" %>
    <%= link_to "駐輪場一覧 /", admin_bicycle_parkings_path, class: "text-gray-500" %>
    <div class="text-blue-500">
      駐輪場作成
    </div>
    </div>
  </div>
  <%= render "form", bicycle_parking: @bicycle_parking %>
</div>

app/views/admin/bicycle_parkings/show.html.erb
<div class="flex flex-col gap-3 md:flex-row md:justify-between mb-4">
  <div class="text-xm font-bold">
    <%= @bicycle_parking.name %>
  </div>
  <div class="flex items-center gap-2 text-xs">
    <%= link_to "ダッシュボード /", admin_root_path, class: "text-gray-500" %>
    <%= link_to "駐輪場一覧 /", admin_bicycle_parkings_path, class: "text-gray-500" %>
    <div class="text-blue-500">
      <%= @bicycle_parking.name %>
    </div>
  </div>
</div>
<div class="px-4 bg-white text-xs md:text-sm rounded">
  <div class="flex justify-between py-2 border-b border-neutral-200">
    <div class="flex items-center gap-2">
      <%= @bicycle_parking.name %>
      <span class="<%= status_style(@bicycle_parking) %>"><%= status_text(@bicycle_parking) %></span>
    </div>
    <div class="flex gap-2">
      <div data-controller="popover">
        <%= link_to edit_admin_bicycle_parking_path(@bicycle_parking), data: { action: "mouseenter->popover#show mouseleave->popover#hide" }, class: "text-red-500 hover:text-red-70 relative" do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0 1 15.75 21H5.25A2.25 2.25 0 0 1 3 18.75V8.25A2.25 2.25 0 0 1 5.25 6H10" />
          </svg>
          <template data-popover-target="content">
            <div data-popover-target="card">
              <p class="absolute top-[-22px] left-[-6px] bg-white rounded text-xs w-[40px] py-1 text-center shadow">編集</p>
            </div>
          </template>
        <% end %>
      </div>
      <div data-controller="popover">
        <%= button_to admin_bicycle_parking_path(@bicycle_parking), method: :delete, data: { action: "mouseenter->popover#show mouseleave->popover#hide", turbo_confirm: "本当に削除しますか？" }, class: "text-red-500 hover:text-red-700 flex relative" do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
          </svg>
          <template data-popover-target="content">
            <div data-popover-target="card">
              <p class="absolute top-[-22px] left-[-6px] bg-white rounded text-xs w-[40px] py-1 text-center shadow">削除</p>
            </div>
          </template>
        <% end %>
      </div>
    </div>
  </div>
  <div class="grid md:grid-cols-5 gap-4 py-2">
    <div class="flex flex-col md:col-span-3 gap-4 z-0">
      <div class="flex justify-between ">
        <div>
          <div>
            <%= "#{BicycleParking.human_attribute_name(:location)}：#{@bicycle_parking.location}" %>
          </div>
          <div class="mt-4">
            <%= "#{BicycleParking.human_attribute_name(:opening_hours)}：#{@bicycle_parking.opening_hours}" %>
          </div>
          <div class="mt-4">
            <%= "#{BicycleParking.human_attribute_name(:bicycle_capacity)}：#{@bicycle_parking.bicycle_capacity}台" %>
          </div>
        </div>
        <div>
          <%= image_tag @bicycle_parking.image, class: "max-h-[90px] rounded" if @bicycle_parking.image.attached? %>
        </div>
      </div>
      <div>
        <%= "#{BicycleParking.human_attribute_name(:motorized_bicycle_under_50cc_capacity)}：#{@bicycle_parking.motorized_bicycle_under_50cc_capacity}台" %>
      </div>
      <div>
        <%= "#{BicycleParking.human_attribute_name(:motorized_bicycle_under_125cc_capacity)}：#{@bicycle_parking.motorized_bicycle_under_125cc_capacity}台" %>
      </div>
      <div>
        <%= "#{BicycleParking.human_attribute_name(:bicycle_and_motorized_bicycle_under_50cc_capacity)}：#{@bicycle_parking.bicycle_and_motorized_bicycle_under_50cc_capacity}台" %>
      </div>
      <div>
        <%= "#{BicycleParking.human_attribute_name(:motorcycle_capacity)}：#{@bicycle_parking.motorcycle_capacity}台" %>
      </div>
      <div>
        <%= "#{BicycleParking.human_attribute_name(:motorcycle_price)}：#{@bicycle_parking.motorcycle_price}円" %>
      </div>
    </div>
    <div class="relative h-[300px] md:col-span-2">
      <div
        id="map"
        class="absolute  h-[100%] top-0 left-0 z-20"
        data-controller="map"
        data-map-target="map"
        data-mapbox-access-token="<%= @mapbox_access_token %>"
        data-mapbox-japan-style="<%= @mapbox_japan_style %>"
        data-image-path="<%= image_path("bicycle.png") %>">
        <input type="hidden" id="data" value="<%= @bicycle_parking_information.to_json %>">
      </div>
    </div>
  </div>
</div>